name: runcontrol
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib>=3.10.0
  - numpy>=2.1.0
  - pandas>=2.2.0
  - paramiko>=3.5.0
  - pip>=24.2
  - python>=3.13
  - pip:
    - PySide6>=6.8.0
    - pyqtgraph>=0.13.7
    - pymysql>=1.1.0
    - mysql-connector-python>=9.1.0
    - sshtunnel>=0.4.0
    - pyusb>=1.2.0
