name: runcontrol
channels:
  - conda-forge
dependencies:
  - matplotlib>=3.10.0
  - numpy>=2.1.0
  - pandas>=2.2.0
  - paramiko>=3.5.0
  - pip>=25.0
  - pybind11>=2.12
  - python>=3.13
  - PySide6>=6.8.0
  - pyqtgraph>=0.13.7
  - pymodbus>=3.9.0
  - pymysql>=1.1.0
  - mysql-connector-python>=9.0.0
  - sshtunnel>=0.4.0
  - pyusb>=1.2.0
  - wheel>=0.45.0
  - setuptools>=75.0.0
  - sphinx>=7.1.2
  - sphinx-rtd-theme>=1.3.0
  - myst-parser>=4.0.0
  - pip:
    - git+https://github.com/SBC-Collaboration/SBCBinaryFormat.git@master#subdirectory=python
    - git+https://github.com/shengzhiheng/RedDigitizerplusplus.git@master
