name: runcontrol
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - numpy>=1.26.0
  - pandas>=2.1.1
  - paramiko>=2.8.1
  - pip>=23.3.1
  - python>=3.11
  - pip:
    - PySide6>=6.6.0
    - pymysql>=1.1.0
    - mysql-connector-python>=8.3.0
    - sshtunnel>=0.4.0
