name: runcontrol
channels:
  - conda-forge
dependencies:
  - matplotlib>=3.10
  - numpy>=2.3
  - pandas>=2.3
  - paramiko>=3.5
  - pip>=25.0
  - pybind11>=3.0
  - python==3.13
  - PySide6==6.8.3
  - pyqtgraph>=0.13
  - pymodbus>=3.11
  - pymysql>=1.1
  - mysql-connector-python>=9.3
  - sshtunnel>=0.4
  - wheel>=0.45
  - setuptools>=80.0
  - setuptools-scm>=8.0
  - sphinx>=8.2
  - sphinx-rtd-theme>=3.0
  - myst-parser>=4.0
  - pip:
    - git+https://github.com/SBC-Collaboration/SBCBinaryFormat.git@master#subdirectory=python
    - git+https://github.com/shengzhiheng/RedDigitizerplusplus.git@master
    - git+https://github.com/shengzhiheng/NI_USB-6501.git@master
